workflows:
  mobile-ios:
    name: Capsin Mobile iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups: []
    working_directory: mobile
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Generate iOS project
        script: flutter create --platforms ios .
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - mobile/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_API_ISSUER_ID
        api_key: $APP_STORE_CONNECT_API_PRIVATE_KEY
